### ISSUE TITLE
如何设置默认主页 + favicon

### ISSUE THREAD

**Issue by mazzzystar** [bill-xia/hexo-theme-mashiro#6]
谢谢您的主题，超级好看！
有如下一些疑惑：
## 1.如何把archive这个页面设置为默认主页呢
希望主页是文章列表。
我尝试在`_config.mashiro.yml`下把：
```yaml
menu:
  Home: /     => Home: /archives
  Archives: /archives
  # About: /about
```
但似乎并不生效。

## 2.设置favicon
我有按照您的README来设置，将`favicon.ico`放置在source下，但执行`hexo clean`时会报错：
```bash
>>>hexo clean
INFO  Validating config
FATAL YAMLException: bad indentation of a mapping entry (32:9)

 29 | show_count: false
 30 | recent_posts_limits: 5
 31 |
 32 |  favicon: favicon.ico
--------------^
 33 | # rss: /atom.xml
 34 |
    at generateError (/Users/X/Documents/Blog/blog/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/Users/X/Documents/Blog/blog/node_modules/js-yaml/lib/loader.js:187:9)
    at readBlockMapping (/X/Documents/Blog/blog/node_modules/js-yaml/lib/loader.js:1182:7)
    at composeNode (/Users/X/Documents/Blog/blog/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/Users/X/Documents/Blog/blog/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/Users/X/Documents/Blog/blog/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/Users/X/Documents/Blog/blog/node_modules/js-yaml/lib/loader.js:1714:19)
    at Hexo.yamlHelper (/Users/X/Documents/Blog/blog/node_modules/hexo/lib/plugins/renderer/yaml.js:20:15)
    at Hexo.tryCatcher (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/X/Documents/Blog/blog/node_modules/hexo/lib/hexo/render.js:81:22
    at tryCatcher (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/X/Documents/Blog/blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21) {
  reason: 'bad indentation of a mapping entry',
  mark: {
    name: null,
    buffer: '# Header\n' +
      'menu:\n' +
      '  Home: /\n' +
      '  Archives: /archives\n' +
      '  # About: /about\n' +
      '\n' +
      '# Content\n' +
      'excerpt_link: Read More\n' +
      'fancybox: true\n' +
      '\n' +
      '# Sidebar\n' +
      '# sidebar: none\n' +
      '# widgets:\n' +
      '# - recent_posts\n' +
      '# - category\n' +
      '# - tagcloud\n' +
      '\n' +
      '# copyright: |-\n' +
      '#   <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a></br>\n' +
      '#   All website licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a></br>\n' +
      '\n' +
      '# toc open \n' +
      'toc:\n' +
      '  enable: true\n' +
      '  default: false\n' +
      '\n' +
      '# Widget behavior\n' +
      "archive_type: 'monthly'\n" +
      'show_count: false\n' +
      'recent_posts_limits: 5\n' +
      '\n' +
      ' favicon: favicon.ico\n' +
      '# rss: /atom.xml\n' +
      '\n' +
      '# valine comment system. https://valine.js.org\n' +
      'valine:\n' +
      '  enable: false # if you want use valine,please set this value is true\n' +
      '  appId:  # leancloud application app id\n' +
      '  appKey:  # leancloud application app key\n' +
      '  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki\n' +
      '  verify: false # valine verify code (true/false)\n' +
      '  pageSize: 10 # comment list page size\n' +
      '  avatar: mm # gravatar style https://valine.js.org/#/avatar\n' +
      '  lang: zh-cn # i18n: zh-cn/en\n' +
      '  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )\n' +
      '  guest_info: nick,mail,link #valine comment header info\n' +
      '\n' +
      'math:\n' +
      '  enable: true\n' +
      '  engine: mathjax\n' +
      '\n' +
      '# title-number : all | config | none\n' +
      'title-number: config\n' +
      '\n' +
      '# blockquote: italic | grey\n' +
      'blockquote: grey\n',
    position: 699,
    line: 31,
    column: 8,
    snippet: ' 29 | show_count: false\n' +
      ' 30 | recent_posts_limits: 5\n' +
      ' 31 | \n' +
      ' 32 |  favicon: favicon.ico\n' +
      '--------------^\n' +
      ' 33 | # rss: /atom.xml\n' +
      ' 34 | '
  }
}
```

**Comment by bill-xia** [comment]
第一个问题等我看一下，您改的地方设置的是导航栏的链接，不会改变主页的渲染模版。具体应该怎么改我需要再看看。
第二个问题是favicon前面多了一个空格，他报错是说缩进有问题，去掉就可以了。

**Comment by bill-xia** [comment]
第一个问题需要您手动改下源码，`layout/index.ejs` 里将 `pagination:2` 改成一个不为 2 的值就可以了。另外还可以在archive页显示文章流，在站点配置里（根目录下的 `_config.yml` 文件）加上`archive: 2`即可。
这个我没法直接改掉合进主线里，否则老用户更新主题之后还得重写配置，见谅。

**Comment by mazzzystar** [comment]
另外，我发现您的网站加载有点慢(已经从README得到预期了)，猜测可能是字体问题，就擅自将以下几个大文件字体中，除了`FZKTJW.ttf`(方正楷体)之外的都删除了：
![2721667640892_ pic](https://user-images.githubusercontent.com/6824141/200113427-e13b90fa-a0a1-4099-8a28-3d166ba74023.jpg)

发现网页渲染结果差异不大，但速度似乎并没有变快。如果我想优化打开速度，该做哪些方面的尝试呢？

**Comment by bill-xia** [comment]
也许可以像这样看看开发者工具栏里哪块加载得比较慢。
<img width="1440" alt="截屏2022-11-05 17 38 25" src="https://user-images.githubusercontent.com/51777099/200113481-af7238ac-ebd3-43f1-9395-4a88fc08329f.png">
我看您搭在`github.io`上，猜测国内访问`github.io`本身就很慢，没什么好办法。

**Comment by mazzzystar** [comment]
多谢，我可以自己调试了。
另外不知何故，我的`FZKTJW.ttf`似乎在用`spider-font`压缩后并没有完整渲染(如下图左下角所示)，我可能不打算压缩了。

![4031667662547_ pic_hd](https://user-images.githubusercontent.com/6824141/200128436-ae2a0eb1-7a51-42d9-974e-494e1994bc0c.jpg)

**Comment by bill-xia** [comment]
如果您还想进行压缩的话，可以看一下font-spider压缩的日志，他会打印所有已经找到的字。如果那里没有出现您要的字就是主题的问题，如果那里出现了您要的字就是浏览器的问题，例如缓存。
另外 `hexo g` 的时候如果有黄色的警告日志打印出来也可以参考。
我对这个不一致的问题也比较好奇，所以如果您还感兴趣可以继续把信息贴在这里来讨论。

**Comment by mazzzystar** [comment]
```bash
> hexo clean
INFO  Validating config
INFO  Deleted database.
INFO  Deleted public folder.

> hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 228 ms
INFO  Generated: archives/index.html
INFO  Generated: sound/index.html
INFO  Generated: about/index.html
INFO  Generated: fancybox/blank.gif
INFO  Generated: archives/2022/04/index.html
INFO  Generated: fancybox/fancy_loading.png
INFO  Generated: fancybox/fancy_nav_left.png
INFO  Generated: fancybox/fancy_nav_right.png
INFO  Generated: fancybox/fancy_shadow_n.png
INFO  Generated: fancybox/fancy_close.png
INFO  Generated: favicon.png
INFO  Generated: fancybox/fancy_shadow_ne.png
INFO  Generated: fancybox/fancy_shadow_w.png
INFO  Generated: fancybox/fancy_shadow_nw.png
INFO  Generated: fancybox/fancy_shadow_sw.png
INFO  Generated: fancybox/fancy_title_left.png
INFO  Generated: fancybox/fancy_shadow_e.png
INFO  Generated: fancybox/fancy_title_main.png
INFO  Generated: fancybox/fancy_shadow_s.png
INFO  Generated: fancybox/fancy_title_right.png
INFO  Generated: fancybox/fancy_title_over.png
INFO  Generated: images/2022-09-07/img_2.jpg
INFO  Generated: fancybox/fancybox-x.png
INFO  Generated: fancybox/fancybox-y.png
INFO  Generated: categories/小说/index.html
INFO  Generated: fancybox/fancy_shadow_se.png
INFO  Generated: favicon.ico
INFO  Generated: index.html
INFO  Generated: archives/2022/09/index.html
INFO  Generated: archives/2022/07/index.html
INFO  Generated: css/fonts/fontawesome-webfont.woff
INFO  Generated: js/clipboard.min.js
INFO  Generated: fancybox/fancybox.png
INFO  Generated: categories/玩/index.html
INFO  Generated: archives/2022/index.html
INFO  Generated: images/2022-09-07/img.jpg
INFO  Generated: fancybox/jquery.fancybox-1.3.4.css
INFO  Generated: fancybox/jquery.fancybox-1.3.4.js
INFO  Generated: fancybox/jquery.mousewheel-3.0.4.pack.js
INFO  Generated: js/jquery-1.4.3.min.js
INFO  Generated: css/fonts/fontawesome-webfont.woff2
INFO  Generated: fancybox/jquery.easing-1.3.pack.js
INFO  Generated: css/fonts/lmroman10-bold.ttf
INFO  Generated: css/fonts/lmroman10-regular.ttf
INFO  Generated: css/fonts/lmroman10-bolditalic.ttf
INFO  Generated: css/fonts/lmroman10-italic.ttf
INFO  Generated: images/2022-09-07/img_1.jpg
INFO  Generated: archives/2022/05/index.html
INFO  Generated: fancybox/jquery.fancybox-1.3.4.pack.js
INFO  Generated: css/fonts/fontawesome-webfont.eot
INFO  Generated: images/2022-09-07/img_3.jpg
INFO  Generated: css/style.css
INFO  Generated: css/fonts/biaodian.ttf
INFO  Generated: js/script.js
INFO  Generated: css/fonts/fontawesome-webfont.ttf
INFO  Generated: css/fonts/lmmono10-regular.ttf
INFO  Generated: 2022/09/07/stable-diffusion/index.html
INFO  Generated: css/fonts/lmmono10-italic.ttf
INFO  Generated: mathjax/output/chtml.js
INFO  Generated: 2022/04/05/generative-art-article-translation/index.html
INFO  Generated: 2022/05/09/clone-virtual-ai/index.html
INFO  Generated: mathjax/tex-chtml.js
INFO  Generated: 2022/07/09/A-Murder/index.html
INFO  Generated: 2022/05/04/how-ai-art-works-1/index.html
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Bold.woff
INFO  Generated: css/fonts/fontawesome-webfont.svg
INFO  Generated: mathjax/output/chtml/fonts/tex.js
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Math-BoldItalic.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Italic.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Size1-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Fraktur-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Bold.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Script-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Bold.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Math-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Size4-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Size2-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Zero.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Vector-Bold.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Fraktur-Bold.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Typewriter-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Size3-Regular.woff
INFO  Generated: mathjax/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff
INFO  Generated: images/2022-11-05/IMG_3456.jpg
INFO  Generated: css/fonts/FZHTJW.ttf
INFO  Generated: css/fonts/FZKTJW.ttf
INFO  Generated: css/fonts/HYFangSongJ.ttf
INFO  Generated: css/fonts/HYShuSongErS.ttf
INFO  94 files generated in 193 ms

> font-spider public/*.html public/*/*.html public/*/*/*.html public/*/*/*/*.html
Font family: FontAwesome
Original size: 165.548 KB
Include chars: 
Chars length: 3
Font id: fb1aeab76ada3ac6738d9574aa338b38
CSS selectors: .nav-icon, .search-form-submit, .article-comment-link:before, .article-share-link:before, .article-share-twitter:before, .article-share-facebook:before, .article-share-pinterest:before, .article-share-linkedin:before, #main-nav-toggle:before
Font files:
File public/css/fonts/fontawesome-webfont.eot created: 2.6 KB
File public/css/fonts/fontawesome-webfont.woff2 created: 1.06 KB
File public/css/fonts/fontawesome-webfont.woff created: 2.496 KB
File public/css/fonts/fontawesome-webfont.ttf created: 2.42 KB
File public/css/fonts/fontawesome-webfont.svg created: 2.338 KB

Font family: LM-Mono-10
Original size: 64.684 KB
Include chars:
Chars length: 0
Font id: 7802ae59e82ade76db02bf2168980831
CSS selectors: .article-entry pre, .article-entry code, .article-entry .gist .gist-file
Font files:
File public/css/fonts/lmmono10-regular.ttf created: 64.684 KB

Font family: LM-Mono-10
Original size: 63.584 KB
Include chars:
Chars length: 0
Font id: abbfe36cb81e527277ae14d9ce905b76
CSS selectors: .article-entry pre, .article-entry code, .article-entry .gist .gist-file
Font files:
File public/css/fonts/lmmono10-italic.ttf created: 63.584 KB

Font family: LM-Roman-10
Original size: 111.536 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: ee9453a93e9e7b215c692c8f5d70c715
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/lmroman10-regular.ttf created: 111.536 KB

Font family: LM-Roman-10
Original size: 118.828 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: 93421a1b7689125b43bff5c92d08ea0a
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/lmroman10-italic.ttf created: 118.828 KB

Font family: LM-Roman-10
Original size: 111.24 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: 2444fb30a02ca9c5917dbd249cd3a93a
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/lmroman10-bold.ttf created: 111.24 KB

Font family: LM-Roman-10
Original size: 118.204 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: 65442d87232a49a82275f21c28d52879
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/lmroman10-bolditalic.ttf created: 118.204 KB

Font family: Chinese
Original size: 14215.408 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: 1d2ff862bb98ba180f61b3e2b7121c2a
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/HYShuSongErS.ttf created: 62.512 KB

Font family: Chinese
Original size: 3190.376 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: 91db8d4c5164bb349ea7039361280186
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/FZHTJW.ttf created: 53.064 KB

Font family: Chinese
Original size: 3927.98 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: f78a7f10e936aa6f8ff5aab81cf6b979
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/FZKTJW.ttf created: 71.94 KB

Font family: ChineseMono
Original size: 4719.24 KB
Include chars:
Chars length: 0
Font id: 95acaabdafbcf2363dc9e965a39f6e39
CSS selectors: .article-entry pre, .article-entry code, .article-entry .gist .gist-file
Font files:
File public/css/fonts/HYFangSongJ.ttf created: 1.9 KB

Font family: biaodian
Original size: 28.152 KB
Include chars: $'(),-./0124579:;=ADGHIJLMNPRST[\]abcdefhilmnoprstuvwxy{}©、。一下不与个中为么义乎乐买了事于些产人什以们件会但使信偏做克入关内决几出制刻剧动单即原发只可台各后含吹和喜器噪在地声备复头奏如始子它完定容对尾己巷并开弹录很快息情想感成我执拟推故敏数整新族无早是普曲更最有未本术杀来果次欢比没法活然照爱现理瓜生用由画的着碎种程类级纯练绘续自色艺萌虚街解言设译话语谱购起身过近这造遍那酷里量陆隆音，：？
Chars length: 226
Font id: 87b89b547500bdad74f7f3f4815bb995
CSS selectors: body, #main-404, .article-entry blockquote, body:before, body:after, .outer:before, .outer:after, #main-nav-toggle:before, .archives:before, .archives:after, .article-entry:before, .article-entry:after, .article-meta:before, .article-meta:after, .article-footer:before, .article-footer:after, .bd-box .bd-beg:not(:last-child):after
Font files:
File public/css/fonts/biaodian.ttf created: 3.144 KB

> hexo d
INFO  Validating config
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
枚举对象中: 24, 完成.
对象计数中: 100% (24/24), 完成.
使用 8 个线程进行压缩
压缩对象中: 100% (14/14), 完成.
写入对象中: 100% (14/14), 129.67 KiB | 506.00 KiB/s, 完成.
总共 14（差异 3），复用 0（差异 0），包复用 0
remote: Resolving deltas: 100% (3/3), completed with 1 local object.
To github.com:mazzzystar/mazzzystar.github.io.git
   649f961..cfb33e3  HEAD -> master
分支 'master' 设置为跟踪 'git@github.com:mazzzystar/mazzzystar.github.io.git/master'。
INFO  Deploy done: git
```

看日志除了中文结尾有1个乱码之外，似乎没问题，但`deploy`之后，[最新版网页](https://mazzzystar.github.io/2022/04/05/generative-art-article-translation/)原本应该是楷体的地方，渲染还是有问题：
<img width="733" alt="image" src="https://user-images.githubusercontent.com/6824141/200150760-6498744f-23bb-430f-8abb-dc30811950ad.png">

**Comment by bill-xia** [comment]
我看日志里已经缺字了，例如“因”字。也许是 font-spider 那个命令应该再加一层嵌套：

```
font-spider public/*.html public/*/*.html public/*/*/*.html public/*/*/*/*.html public/*/*/*/*/*.html --no-backup
```

**Comment by mazzzystar** [comment]
多谢，确实是层数不够导致，增加层数后问题被修复。
<img width="333" alt="image" src="https://user-images.githubusercontent.com/6824141/200733915-8e8dc08f-e75d-4cbe-86a6-6925d1bb7eab.png">

但不知为何，这个改变导致最新版网站所有的标题都加粗了。
https://mazzzystar.github.io/archives/

**Comment by bill-xia** [comment]
这是主题的一部分，正常情况下字体就是这样的。我看您现在正文也变成宋体了。
让正文变成普通的黑体需要删除HYShuSongErS.ttf，让标题变成普通的字体需要删除 FZHTJW.ttf。

**Comment by mazzzystar** [comment]
谢谢您，最后配置成这样满足了我的需求:-D
<img width="544" alt="image" src="https://user-images.githubusercontent.com/6824141/200740766-5597e500-c206-4bed-b166-b91227202210.png">
